debug: true

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:4306/backup_media?serverTimezone=UTC"
    username: root
    password: 123456

backup:
  media:
    sourcePath: "asdf"
    targetPath: "dddd"