debug: true

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:4306/backup_media?serverTimezone=UTC"
    username: root
    password: 123456

backup:
  media:
    sourcePath: "Z:\\verysyncbackup"
    targetPath: "E:\\TimeMachine"
    uncategorizedPath: "E:\\TimeMachine\\UNKNOWN"
    excludeFolderName:
      - ".verysync"
      - ".trash"
      - "cache"
      - "Alipay"
      - "snapseed"
      - "sound"
      - "com.baidu.BaiduMap"
      - "douyin"
      - "hiddenAlbum"
      - "Lark"
      - "Screenshots"
      - "taobao"
      - "HuaweiHealth"
      - "Pindd"
      - "证件"
      - "婚纱"
      - "结婚"
      - "jerry-xiaomi"
      - "mary-iphone"
      - "Mi Note 2"
      - "马丽的 iPhone"
    excludeFileName:
      - ".pending-"
      - ".camera.jpg"
      - "tb_image_share"