CREATE TABLE IF NOT EXISTS `media`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `filename` VARCHAR(50) NOT NULL DEFAULT '',
    `type` TINYINT(3) NOT NULL,
    `source_path` VARCHAR(255) NOT NULL DEFAULT '',
    `target_path` VARCHAR(255) NOT NULL DEFAULT '',
    `result` TINYINT(3) NOT NULL ,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    key `index_filename` (`filename`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;